version: "3.8"
services:
    php:
        container_name: php
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: tadam-space
            MYSQL_USER: db
            MYSQL_PASSWORD: 123456
        ports:
            - "9906:3306"
    pma:
        container_name: pma
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
